import { useState, useRef, useEffect, useCallback } from 'react'
import { supabase } from '../supabaseClient'
import { GREEN, LIGHT_GREEN, TEXT, MUTED, BORDER, BG, PAGE_BG, NAVY, NAVY_LIGHT, NAVY_MUTED, AMBER, AMBER_BG, AMBER_TEXT, TRIAL_LIMITS, BASIC_LIMITS, PREMIUM_LIMITS, STRIPE_PRICES, s } from '../constants'

export function ResourceDownloadButton({ resource }) {
  const [open, setOpen] = useState(false)
  const [downloading, setDownloading] = useState(null)
  const [dropPos, setDropPos] = useState({ top: 0, left: 0 })
  const btnRef = useRef(null)
  const ref = useRef(null)

  useEffect(() => {
    function handleClick(e) { if (ref.current && !ref.current.contains(e.target)) setOpen(false) }
    document.addEventListener('mousedown', handleClick)
    return () => document.removeEventListener('mousedown', handleClick)
  }, [])

  function openDropdown() {
    if (btnRef.current) {
      const rect = btnRef.current.getBoundingClientRect()
      setDropPos({ top: rect.top - 4, left: rect.right })
    }
    setOpen(o => !o)
  }

  async function handle(format) {
    setOpen(false); setDownloading(format)
    const res = { title: resource.title, meta: resource.meta, sections: resource.sections }
    try {
      if (format === 'txt') {
        const lines = [res.title, '='.repeat(60), res.meta || '', '']
        res.sections?.forEach(sec => { lines.push(sec.heading.toUpperCase()); lines.push('-'.repeat(40)); lines.push(sec.content); lines.push('') })
        const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a'); a.href = url; a.download = `${res.title.replace(/[^a-z0-9]/gi, '_')}.txt`; a.click()
        URL.revokeObjectURL(url)
      } else if (format === 'pdf') {
        await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js')
        const { jsPDF } = window.jspdf
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
        const GREEN_RGB = [29,158,117], NAVY_RGB = [30,36,51], MUTED_RGB = [95,94,90]
        const margin = 18, pageW = 210, contentW = pageW - margin * 2
        let y = 0
        function addPage() { doc.addPage(); y = 18 }
        function checkY(n=10) { if (y+n>275) addPage() }
        function body(text, size=10) {
          if (!text) return; checkY(8)
          doc.setFontSize(size); doc.setTextColor(...MUTED_RGB); doc.setFont('helvetica','normal')
          const lines = doc.splitTextToSize(String(text), contentW)
          doc.text(lines, margin, y); y += lines.length*(size*0.45)+2
        }
        doc.setFillColor(...NAVY_RGB); doc.rect(0,0,pageW,32,'F')
        doc.setFontSize(14); doc.setTextColor(255,255,255); doc.setFont('helvetica','bold')
        doc.text(res.title, margin, 13)
        doc.setFontSize(9); doc.setFont('helvetica','normal'); doc.setTextColor(139,147,167)
        doc.text(res.meta||'', margin, 22)
        y = 40
        res.sections?.forEach(sec => {
          checkY(14); doc.setFillColor(...GREEN_RGB); doc.roundedRect(margin, y-4, contentW, 7, 1.5, 1.5, 'F')
          doc.setFontSize(9); doc.setTextColor(255,255,255); doc.setFont('helvetica','bold')
          doc.text(sec.heading.toUpperCase(), margin+4, y+0.5); y += 9
          body(sec.content); y += 4
        })
        doc.save(`${res.title.replace(/[^a-z0-9]/gi, '_')}.pdf`)
      } else if (format === 'docx') {
        await loadScript('https://cdn.jsdelivr.net/npm/docx@7.8.2/build/index.js')
        await loadScript('https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js')
        const { Document, Packer, Paragraph, TextRun, ShadingType, AlignmentType } = window.docx
        const saveAs = window.saveAs || (window.FileSaver && window.FileSaver.saveAs)
        const children = [
          new Paragraph({ children: [new TextRun({ text: res.title, bold: true, color: '1E2433', size: 36 })], spacing: { after: 80 } }),
          new Paragraph({ children: [new TextRun({ text: res.meta||'', color: '5F5E5A', size: 18, italics: true })], spacing: { after: 400 } }),
          ...(res.sections?.flatMap(sec => [
            new Paragraph({ children: [new TextRun({ text: sec.heading, bold: true, color: 'FFFFFF', size: 22 })], shading: { type: ShadingType.SOLID, color: '1D9E75' }, spacing: { before: 300, after: 140 }, indent: { left: 100, right: 100 } }),
            new Paragraph({ children: [new TextRun({ text: sec.content, color: '5F5E5A', size: 20 })], spacing: { after: 200 }, indent: { left: 100 } }),
          ]) || []),
          new Paragraph({ children: [new TextRun({ text: 'Generated by TeachReads', color: 'B4B2A9', size: 16, italics: true })], spacing: { before: 600 }, alignment: AlignmentType.CENTER }),
        ]
        const docFile = new Document({ sections: [{ properties: {}, children }] })
        const blob = await Packer.toBlob(docFile)
        saveAs(blob, `${res.title.replace(/[^a-z0-9]/gi, '_')}.docx`)
      }
    } catch(e) { console.error('Download error:', e) }
    setDownloading(null)
  }

  return (
    <div ref={ref} style={{ position: 'relative' }} onClick={e => e.stopPropagation()}>
      <button ref={btnRef} onClick={openDropdown} disabled={!!downloading}
        style={{ height: 26, padding: '0 8px', background: PAGE_BG, border: `0.5px solid ${BORDER}`, borderRadius: 6, fontSize: 11, color: MUTED, cursor: downloading ? 'wait' : 'pointer', fontFamily: "'DM Sans', sans-serif", display: 'inline-flex', alignItems: 'center', gap: 3 }}>
        {downloading ? '⏳' : '⬇'}
      </button>
      {open && (
        <div style={{ position: 'fixed', top: dropPos.top, left: dropPos.left, transform: 'translate(-100%, -100%)', background: BG, border: `0.5px solid ${BORDER}`, borderRadius: 10, width: 160, boxShadow: '0 8px 24px rgba(0,0,0,0.15)', overflow: 'hidden', zIndex: 9999 }}>
          <div style={{ padding: '7px 12px 5px', fontSize: 10, color: MUTED, fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.06em', borderBottom: `0.5px solid ${BORDER}` }}>Download as</div>
          {[['pdf','📄 PDF','Print-ready'],['docx','📝 Word','Editable'],['txt','📃 Text','Plain text']].map(([id,label,desc]) => (
            <div key={id} onClick={() => handle(id)}
              style={{ padding: '8px 12px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}
              onMouseEnter={e => e.currentTarget.style.background = PAGE_BG}
              onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>
              <span style={{ fontSize: 12, color: TEXT, fontWeight: 500 }}>{label}</span>
              <span style={{ fontSize: 10, color: MUTED }}>{desc}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

export function ResourcesPage({ onNavigate, checkTrial }) {
  const [tab, setTab] = useState('adhoc') // 'adhoc' | 'plan' | 'catalogue'
  const [catalogue, setCatalogue] = useState([])
  const [catalogueLoading, setCatalogueLoading] = useState(false)
  const [catalogueSearch, setCatalogueSearch] = useState('')
  const [catalogueType, setCatalogueType] = useState('All')
  const [catalogueSubject, setCatalogueSubject] = useState('All')
  const [catalogueYear, setCatalogueYear] = useState('All')
  const [viewingResource, setViewingResource] = useState(null)

  async function loadCatalogue() {
    setCatalogueLoading(true)
    const { data: { user } } = await supabase.auth.getUser()
    const { data, error } = await supabase
      .from('resources')
      .select('*')
      .eq('user_id', user?.id)
      .order('created_at', { ascending: false })
    if (!error) setCatalogue(data || [])
    else console.error('loadCatalogue error:', error)
    setCatalogueLoading(false)
  }

  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (tab === 'catalogue') loadCatalogue() }, [tab])

  // Plan-based state
  const [realPlans, setRealPlans] = useState([])
  const [selectedPlanGroup, setSelectedPlanGroup] = useState(null)
  const [selectedPlan, setSelectedPlan] = useState(null)
  const [selectedLesson, setSelectedLesson] = useState(null)
  const [selectedResourceType, setSelectedResourceType] = useState(null)
  const [planSearch, setPlanSearch] = useState('')
  const [planFilterSubject, setPlanFilterSubject] = useState('All')
  const [planFilterYear, setPlanFilterYear] = useState('All')
  const [planDropdownOpen, setPlanDropdownOpen] = useState(false)
  const [realLessons, setRealLessons] = useState([])

  useEffect(() => {
    if (!selectedPlan?.id) { setRealLessons([]); return }
    supabase.from('lessons')
      .select('lesson_number, title, type, learning_intention')
      .eq('plan_id', selectedPlan.id)
      .order('lesson_number')
      .then(({ data }) => { if (data) setRealLessons(data) })
  }, [selectedPlan?.id])

  useEffect(() => {
    async function loadRealPlans() {
      const { data: { user } } = await supabase.auth.getUser()
      const { data: plans } = await supabase
        .from('plans')
        .select('id, title, subject, year_group, lesson_count, book_title, book_author')
        .eq('user_id', user?.id)
        .order('created_at', { ascending: false })
      if (plans) {
        // Group by book into same shape as DUMMY_PLANS
        const groups = []
        plans.forEach(plan => {
          const existing = groups.find(g => g.book.title === plan.book_title)
          const planEntry = { id: plan.id, title: plan.title, subject: plan.subject, lessons: plan.lesson_count, topic: plan.title }
          if (existing) { existing.plans.push(planEntry) }
          else { groups.push({ book: { title: plan.book_title, author: plan.book_author || '', emoji: '📚' }, yearGroup: plan.year_group, plans: [planEntry] }) }
        })
        setRealPlans(groups)
      }
    }
    loadRealPlans()
  }, [])

  // Ad-hoc state
  const [prompt, setPrompt] = useState('')

  // Shared state
  const [generating, setGenerating] = useState(false)
  const [resource, setResource] = useState(null)
  const [error, setError] = useState('')

  async function generateFromPlan() {
    if (!selectedPlan || !selectedLesson || !selectedResourceType) return
    const allowed = await checkTrial?.('resources')
    if (allowed === false) return
    setGenerating(true); setError(''); setResource(null)
    const rt = RESOURCE_TYPES.find(r => r.id === selectedResourceType)
    const apiPrompt = `You are an expert UK primary school teacher creating a classroom resource.

Book: "${selectedPlanGroup.book.title}" by ${selectedPlanGroup.book.author}
Year group: ${selectedPlanGroup.yearGroup}
Subject: ${selectedPlan.subject}
Lesson: ${selectedLesson.title}
Learning intention: ${selectedLesson.learningIntention || ''}
Resource type: ${rt.label} — ${rt.desc}

Generate a complete, classroom-ready ${rt.label} resource directly tied to this lesson. Return ONLY a valid JSON object with no extra text or markdown fences:

{
  "title": "resource title",
  "meta": "brief one-line description e.g. Year 4 · History · Roman Mosaic Patterns",
  "sections": [
    { "heading": "section heading", "content": "full section content — be detailed and classroom-ready" }
  ]
}

For worksheets: include Below Expectation, At Expectation and Above Expectation sections with differentiated tasks.
For vocab cards: list each term as Term: [word] — Definition: [meaning].
For knowledge organisers: include Key Facts, Key People/Vocabulary, and Key Dates/Events sections.
For all other types: use appropriate sections for the resource type.`

    try {
      const result = await callAPI(apiPrompt, true)
      setResource(result)
      // Save resource to Supabase
      try {
        const { data: { user } } = await supabase.auth.getUser()
        if (user) {
          await supabase.from('resources').insert({
            user_id: user.id,
            plan_id: selectedPlan?.id || null,
            title: result.title,
            meta: result.meta,
            resource_type: selectedResourceType,
            sections: result.sections,
            prompt: apiPrompt,
          })
          loadCatalogue()
        }
      } catch (e) { console.error('Plan resource save error:', JSON.stringify(e)); }
    } catch (err) { console.error('generateFromPlan error:', err); setError('Something went wrong. Please try again.') }
    setGenerating(false)
  }

  async function generateAdhoc() {
    if (!prompt.trim()) return
    const allowed = await checkTrial?.('resources')
    if (allowed === false) return
    setGenerating(true); setError(''); setResource(null)
    const apiPrompt = `You are an expert UK primary school teacher creating a classroom resource.

Teacher request: ${prompt}

Generate a complete, classroom-ready resource based on this request. Return ONLY a valid JSON object with no extra text or markdown fences:

{
  "title": "resource title",
  "meta": "brief one-line description",
  "sections": [
    { "heading": "section heading", "content": "full detailed classroom-ready content" }
  ]
}

Be detailed and practical. If a worksheet is requested, differentiate for different abilities. If specific year group or subject is mentioned, align to the UK National Curriculum.`

    try {
      const result = await callAPI(apiPrompt, true)
      setResource(result)
      // Save resource to Supabase
      try {
        const { data: { user } } = await supabase.auth.getUser()
        if (user) {
          await supabase.from('resources').insert({
            user_id: user.id,
            title: result.title,
            meta: result.meta,
            resource_type: 'adhoc',
            sections: result.sections,
            prompt: prompt,
          })
          loadCatalogue()
        }
      } catch (e) { console.error('Adhoc resource save error:', JSON.stringify(e)); }
    } catch (err) { console.error('generateAdhoc error:', err); setError('Something went wrong. Please try again.') }
    setGenerating(false)
  }

  const EXAMPLE_PROMPTS = [
    "Create a maths worksheet for Year 4 on multiplication, differentiated for below, at and above expectation",
    "Make a Year 2 phonics activity focusing on the 'igh' sound with pictures and tracing",
    "Create a science knowledge organiser for Year 5 on the water cycle",
    "Generate a Year 6 reading comprehension passage and questions about the Vikings",
    "Create a PSHE discussion activity for Year 3 about feelings and emotions",
  ]

  const tabBtn = (id, label, emoji) => (
    <button onClick={() => { setTab(id); setResource(null); setError('') }}
      style={{ flex: 1, height: 42, border: "none", borderBottom: tab === id ? `2px solid ${GREEN}` : "2px solid transparent", background: "transparent", cursor: "pointer", fontSize: 14, fontWeight: tab === id ? 600 : 400, color: tab === id ? GREEN : MUTED, fontFamily: "'DM Sans', sans-serif", display: "flex", alignItems: "center", justifyContent: "center", gap: 6 }}>
      {emoji} {label}
    </button>
  )

  // Plan tab computed values (moved out of IIFE)
  const allPlans = realPlans.flatMap(group => group.plans.map(plan => ({ ...plan, group })))
  const planSubjects = ['All', ...Array.from(new Set(allPlans.map(p => p.subject))).sort()]
  const planYears = ['All', ...Array.from(new Set(allPlans.map(p => p.group.yearGroup))).sort()]
  const filteredPlans = allPlans.filter(p => {
    if (planFilterSubject !== 'All' && p.subject !== planFilterSubject) return false
    if (planFilterYear !== 'All' && p.group.yearGroup !== planFilterYear) return false
    if (planSearch && !p.title.toLowerCase().includes(planSearch.toLowerCase()) &&
        !p.group.book.title.toLowerCase().includes(planSearch.toLowerCase())) return false
    return true
  })

  return (
    <div style={{ ...s.page, maxWidth: "100%" }}>
      <div style={{ maxWidth: 860, margin: "0 auto", padding: "0 1rem" }}>

        {/* Header */}
        <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: "1.75rem" }}>
          <div style={{ width: 52, height: 52, background: GREEN, borderRadius: 12, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, fontSize: 26 }}>🛠️</div>
          <div>
            <h1 style={s.h1}>My Resources</h1>
            <p style={s.headerSub}>Generate and browse all your classroom resources</p>
          </div>
        </div>

        {/* Tabs */}
        <div style={{ background: BG, border: `0.5px solid ${BORDER}`, borderRadius: 12, overflow: "hidden", marginBottom: 16 }}>
          <div style={{ display: "flex", borderBottom: `0.5px solid ${BORDER}` }}>
            {tabBtn('adhoc', 'Quick resource', '⚡')}
            {tabBtn('plan', 'From a plan', '📋')}
            {tabBtn('catalogue', 'My catalogue', '📂')}
          </div>

          <div style={{ padding: "20px" }}>

            {/* ── Ad-hoc tab ── */}
            {tab === 'adhoc' && (
              <div>
                <p style={{ fontSize: 13, color: MUTED, marginBottom: 14, lineHeight: 1.6 }}>
                  Describe the resource you need. Be as specific as you like — include year group, subject, topic, and any differentiation requirements.
                </p>
                <textarea
                  style={{ ...s.textarea, height: 100, borderRadius: 8, borderBottom: `0.5px solid ${BORDER}`, marginBottom: 10, fontSize: 14 }}
                  placeholder='e.g. "Create a maths worksheet for Year 4 on multiplication, differentiated for below, at and above expectation"'
                  value={prompt}
                  onChange={e => setPrompt(e.target.value)}
                />
                {/* Example prompts */}
                <div style={{ marginBottom: 14 }}>
                  <div style={{ fontSize: 11, color: MUTED, fontWeight: 500, marginBottom: 6 }}>EXAMPLE PROMPTS</div>
                  <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                    {EXAMPLE_PROMPTS.map((ex, i) => (
                      <div key={i} onClick={() => setPrompt(ex)}
                        style={{ fontSize: 12, color: GREEN, cursor: "pointer", padding: "6px 10px", background: LIGHT_GREEN, borderRadius: 6, lineHeight: 1.5 }}
                        onMouseEnter={e => e.currentTarget.style.background = '#d1f0e6'}
                        onMouseLeave={e => e.currentTarget.style.background = LIGHT_GREEN}>
                        ⚡ {ex}
                      </div>
                    ))}
                  </div>
                </div>
                <button
                  onClick={generateAdhoc}
                  disabled={generating || !prompt.trim()}
                  style={s.submitBtn(generating || !prompt.trim())}
                >
                  {generating ? '⏳ Generating resource...' : '✨ Generate resource'}
                </button>
              </div>
            )}

            {/* ── Plan-based tab ── */}
            {tab === 'plan' && (() => {

              // Use realLessons from component state (loaded via useEffect)
              const lessonContext = realLessons.length > 0
                ? realLessons.map(l => ({ num: l.lesson_number, title: l.title, type: l.type, intention: l.learning_intention || '' }))
                : Array.from({ length: selectedPlan?.lessons || 0 }, (_, i) => ({ num: i+1, title: `Lesson ${i+1}`, type: '', intention: '' }))

              const typeColors = { Explore: '#7C5CBF', Analyse: '#1D6FA8', Teach: '#1D9E75', Practise: '#D97706', Apply: '#DC6B3A', Create: '#B91C78' }
              const typeBgs = { Explore: '#F3EEFF', Analyse: '#E8F4FF', Teach: '#E1F5EE', Practise: '#FEF3C7', Apply: '#FEF0E8', Create: '#FCE7F3' }

              return (
                <div>
                  <p style={{ fontSize: 13, color: MUTED, marginBottom: 16, lineHeight: 1.6 }}>
                    Select a plan, choose a lesson, then pick what type of resource to generate. The AI will use the full lesson context to create something tailored.
                  </p>

                  {/* Step 1 — Pick a plan with search + filters + dropdown */}
                  <div style={{ marginBottom: 16 }}>
                    <div style={{ fontSize: 11, fontWeight: 600, color: MUTED, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }}>
                      Step 1 — Select a plan
                    </div>

                    {/* Filter row */}
                    <div style={{ display: "flex", gap: 8, marginBottom: 8, flexWrap: "wrap" }}>
                      <div style={{ flex: 1, minWidth: 160, position: "relative" }}>
                        <span style={{ position: "absolute", left: 9, top: "50%", transform: "translateY(-50%)", fontSize: 13, color: MUTED }}>🔍</span>
                        <input
                          style={{ ...s.input, height: 32, fontSize: 12, paddingLeft: 28 }}
                          placeholder="Search plans or books..."
                          value={planSearch}
                          onChange={e => { setPlanSearch(e.target.value); setPlanDropdownOpen(true) }}
                          onFocus={() => setPlanDropdownOpen(true)}
                        />
                      </div>
                      <select value={planFilterSubject} onChange={e => { setPlanFilterSubject(e.target.value); setPlanDropdownOpen(true) }}
                        style={{ height: 32, fontSize: 12, borderRadius: 8, border: `0.5px solid ${planFilterSubject !== 'All' ? GREEN : BORDER}`, padding: "0 10px", background: planFilterSubject !== 'All' ? LIGHT_GREEN : BG, color: planFilterSubject !== 'All' ? '#085041' : TEXT, cursor: "pointer", fontFamily: "'DM Sans', sans-serif", outline: "none" }}>
                        {planSubjects.map(s => <option key={s} value={s}>{s === 'All' ? 'All subjects' : s}</option>)}
                      </select>
                      <select value={planFilterYear} onChange={e => { setPlanFilterYear(e.target.value); setPlanDropdownOpen(true) }}
                        style={{ height: 32, fontSize: 12, borderRadius: 8, border: `0.5px solid ${planFilterYear !== 'All' ? GREEN : BORDER}`, padding: "0 10px", background: planFilterYear !== 'All' ? LIGHT_GREEN : BG, color: planFilterYear !== 'All' ? '#085041' : TEXT, cursor: "pointer", fontFamily: "'DM Sans', sans-serif", outline: "none" }}>
                        {planYears.map(y => <option key={y} value={y}>{y === 'All' ? 'All years' : y}</option>)}
                      </select>
                    </div>

                    {/* Selected plan display or dropdown */}
                    {selectedPlan && !planDropdownOpen ? (
                      <div style={{ padding: "10px 14px", borderRadius: 8, border: `0.5px solid ${GREEN}`, background: LIGHT_GREEN, display: "flex", alignItems: "center", gap: 10 }}>
                        <span style={{ fontSize: 11, fontWeight: 600, padding: "2px 8px", borderRadius: 20, background: GREEN, color: "#fff" }}>{selectedPlan.subject}</span>
                        <div style={{ flex: 1 }}>
                          <div style={{ fontSize: 13, fontWeight: 500, color: "#085041" }}>{selectedPlan.title}</div>
                          <div style={{ fontSize: 11, color: MUTED }}>{selectedPlanGroup.book.title} · {selectedPlanGroup.yearGroup} · {selectedPlan.lessons} lessons</div>
                        </div>
                        <button onClick={() => { setPlanDropdownOpen(true); setSelectedPlan(null); setSelectedLesson(null) }}
                          style={{ fontSize: 11, color: MUTED, background: "none", border: `0.5px solid ${BORDER}`, borderRadius: 6, padding: "3px 8px", cursor: "pointer", fontFamily: "'DM Sans', sans-serif" }}>
                          Change
                        </button>
                      </div>
                    ) : (
                      <div style={{ border: `0.5px solid ${BORDER}`, borderRadius: 8, overflow: "hidden", maxHeight: 260, overflowY: "auto" }}>
                        {filteredPlans.length === 0 ? (
                          <div style={{ padding: "1rem", textAlign: "center", color: MUTED, fontSize: 13 }}>No plans match your filters</div>
                        ) : filteredPlans.map(plan => (
                          <div key={plan.id}
                            onClick={() => { setSelectedPlanGroup(plan.group); setSelectedPlan(plan); setSelectedLesson(null); setPlanDropdownOpen(false) }}
                            style={{ padding: "10px 14px", borderBottom: `0.5px solid ${BORDER}`, display: "flex", alignItems: "center", gap: 10, cursor: "pointer", background: BG }}
                            onMouseEnter={e => e.currentTarget.style.background = PAGE_BG}
                            onMouseLeave={e => e.currentTarget.style.background = BG}>
                            <span style={{ fontSize: 11, fontWeight: 600, padding: "2px 8px", borderRadius: 20, background: PAGE_BG, color: MUTED, flexShrink: 0 }}>{plan.subject}</span>
                            <div style={{ flex: 1, minWidth: 0 }}>
                              <div style={{ fontSize: 13, fontWeight: 500, color: TEXT, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{plan.title}</div>
                              <div style={{ fontSize: 11, color: MUTED }}>{plan.group.book.title} · {plan.group.yearGroup} · {plan.lessons} lessons</div>
                            </div>
                            <span style={{ fontSize: 12, color: GREEN, flexShrink: 0 }}>Select →</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Step 2 — Pick a lesson with context */}
                  {selectedPlan && !planDropdownOpen && (
                    <div style={{ marginBottom: 16 }}>
                      <div style={{ fontSize: 11, fontWeight: 600, color: MUTED, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }}>
                        Step 2 — Select a lesson
                      </div>
                      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                        {lessonContext.map(lesson => {
                          const isSelected = selectedLesson?.num === lesson.num
                          const tc = typeColors[lesson.type] || GREEN
                          const tb = typeBgs[lesson.type] || LIGHT_GREEN
                          return (
                            <div key={lesson.num}
                              onClick={() => setSelectedLesson(lesson)}
                              style={{ padding: "10px 14px", borderRadius: 8, border: `0.5px solid ${isSelected ? GREEN : BORDER}`, background: isSelected ? LIGHT_GREEN : BG, cursor: "pointer", display: "flex", alignItems: "flex-start", gap: 12 }}>
                              {/* Lesson number */}
                              <div style={{ width: 28, height: 28, background: isSelected ? GREEN : PAGE_BG, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 700, color: isSelected ? "#fff" : MUTED, flexShrink: 0, marginTop: 1 }}>
                                {lesson.num}
                              </div>
                              <div style={{ flex: 1 }}>
                                <div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 3 }}>
                                  <span style={{ fontSize: 13, fontWeight: 500, color: isSelected ? "#085041" : TEXT }}>{lesson.title}</span>
                                  <span style={{ fontSize: 10, fontWeight: 600, color: tc, background: tb, padding: "1px 7px", borderRadius: 20 }}>{lesson.type}</span>
                                </div>
                                <div style={{ fontSize: 12, color: MUTED, lineHeight: 1.4 }}>
                                  <span style={{ fontWeight: 500 }}>Learning intention: </span>{lesson.intention}
                                </div>
                              </div>
                              {isSelected && <span style={{ color: GREEN, fontSize: 16, flexShrink: 0, marginTop: 4 }}>✓</span>}
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  )}

                  {/* Step 3 — Pick resource type */}
                  {selectedLesson && (
                    <div style={{ marginBottom: 16 }}>
                      <div style={{ fontSize: 11, fontWeight: 600, color: MUTED, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }}>
                        Step 3 — Choose resource type
                      </div>
                      <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 8 }}>
                        {RESOURCE_TYPES.map(rt => {
                          const isSelected = selectedResourceType === rt.id
                          return (
                            <div key={rt.id}
                              onClick={() => setSelectedResourceType(rt.id)}
                              style={{ padding: "10px 12px", borderRadius: 8, border: `0.5px solid ${isSelected ? GREEN : BORDER}`, background: isSelected ? LIGHT_GREEN : BG, cursor: "pointer", display: "flex", alignItems: "flex-start", gap: 10 }}>
                              <span style={{ fontSize: 20, flexShrink: 0 }}>{rt.emoji}</span>
                              <div>
                                <div style={{ fontSize: 13, fontWeight: 500, color: isSelected ? "#085041" : TEXT }}>{rt.label}</div>
                                <div style={{ fontSize: 11, color: MUTED, lineHeight: 1.4 }}>{rt.desc}</div>
                              </div>
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  )}

                  {/* Generate button */}
                  {selectedResourceType && (
                    <button onClick={generateFromPlan} disabled={generating} style={s.submitBtn(generating)}>
                      {generating ? '⏳ Generating resource...' : '✨ Generate resource'}
                    </button>
                  )}
                </div>
              )
            })()}

          {/* ── Catalogue tab ── */}
            {tab === 'catalogue' && (
              <div>
                {/* Filter bar */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16, flexWrap: 'nowrap' }}>
                  <span style={{ fontSize: 15, color: MUTED, flexShrink: 0 }}>🔍</span>
                  <input
                    style={{ flex: 1, minWidth: 0, height: 28, border: 'none', outline: 'none', fontSize: 13, color: TEXT, background: 'transparent', fontFamily: "'DM Sans', sans-serif" }}
                    placeholder="Search your resources..."
                    value={catalogueSearch}
                    onChange={e => setCatalogueSearch(e.target.value)}
                  />
                  {catalogueSearch && <span onClick={() => setCatalogueSearch('')} style={{ fontSize: 13, color: MUTED, cursor: 'pointer', flexShrink: 0 }}>✕</span>}
                  <select style={{ height: 28, fontSize: 12, border: `0.5px solid ${catalogueType !== 'All' ? GREEN : BORDER}`, borderRadius: 20, padding: '0 10px', background: catalogueType !== 'All' ? LIGHT_GREEN : BG, color: catalogueType !== 'All' ? '#085041' : TEXT, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", outline: 'none', flexShrink: 0 }}
                    value={catalogueType} onChange={e => setCatalogueType(e.target.value)}>
                    <option value="All">All types</option>
                    <option value="worksheet">Worksheet</option>
                    <option value="starter">Lesson starter</option>
                    <option value="exit_ticket">Exit ticket</option>
                    <option value="writing_frame">Writing frame</option>
                    <option value="knowledge_org">Knowledge organiser</option>
                    <option value="vocab_cards">Vocabulary cards</option>
                    <option value="comprehension">Reading comprehension</option>
                    <option value="adhoc">Quick resource</option>
                  </select>
                  <select style={{ height: 28, fontSize: 12, border: `0.5px solid ${catalogueSubject !== 'All' ? GREEN : BORDER}`, borderRadius: 20, padding: '0 10px', background: catalogueSubject !== 'All' ? LIGHT_GREEN : BG, color: catalogueSubject !== 'All' ? '#085041' : TEXT, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", outline: 'none', flexShrink: 0 }}
                    value={catalogueSubject} onChange={e => setCatalogueSubject(e.target.value)}>
                    <option value="All">All subjects</option>
                    {['Art','Computing','DT','Geography','History','Literacy','Maths','Music','PE','PSHE','RE','Science'].map(s => <option key={s} value={s}>{s}</option>)}
                  </select>
                  <select style={{ height: 28, fontSize: 12, border: `0.5px solid ${catalogueYear !== 'All' ? GREEN : BORDER}`, borderRadius: 20, padding: '0 10px', background: catalogueYear !== 'All' ? LIGHT_GREEN : BG, color: catalogueYear !== 'All' ? '#085041' : TEXT, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", outline: 'none', flexShrink: 0 }}
                    value={catalogueYear} onChange={e => setCatalogueYear(e.target.value)}>
                    <option value="All">All years</option>
                    {['Year 1','Year 2','Year 3','Year 4','Year 5','Year 6'].map(y => <option key={y} value={y}>{y}</option>)}
                  </select>
                  <span onClick={loadCatalogue} title="Refresh" style={{ fontSize: 13, color: MUTED, cursor: 'pointer', flexShrink: 0 }}>↺</span>
                </div>

                {catalogueLoading ? (
                  <div style={{ textAlign: 'center', padding: '2rem', color: MUTED, fontSize: 13 }}>Loading your resources...</div>
                ) : (() => {
                  const filtered = catalogue.filter(r => {
                    if (catalogueType !== 'All' && r.resource_type !== catalogueType) return false
                    if (catalogueSubject !== 'All' && !(r.meta || '').toLowerCase().includes(catalogueSubject.toLowerCase())) return false
                    if (catalogueYear !== 'All' && !(r.meta || '').toLowerCase().includes(catalogueYear.toLowerCase())) return false
                    if (catalogueSearch && !r.title.toLowerCase().includes(catalogueSearch.toLowerCase()) &&
                        !(r.meta || '').toLowerCase().includes(catalogueSearch.toLowerCase())) return false
                    return true
                  })
                  const typeLabels = { worksheet: 'Worksheet', starter: 'Lesson starter', exit_ticket: 'Exit ticket', writing_frame: 'Writing frame', knowledge_org: 'Knowledge organiser', vocab_cards: 'Vocabulary cards', comprehension: 'Reading comprehension', adhoc: 'Quick resource' }
                  const typeColors = { worksheet: { bg: '#EEF2FF', color: '#3730A3' }, starter: { bg: '#FEF3C7', color: '#92400E' }, exit_ticket: { bg: '#ECFDF5', color: '#065F46' }, writing_frame: { bg: '#FCE7F3', color: '#9D174D' }, knowledge_org: { bg: '#EFF6FF', color: '#1E40AF' }, vocab_cards: { bg: '#FDF4FF', color: '#7E22CE' }, comprehension: { bg: '#FFF7ED', color: '#9A3412' }, adhoc: { bg: PAGE_BG, color: MUTED } }

                  if (filtered.length === 0) return (
                    <div style={{ textAlign: 'center', padding: '2.5rem', color: MUTED }}>
                      <div style={{ fontSize: 36, marginBottom: 10 }}>📂</div>
                      <div style={{ fontSize: 14, fontWeight: 500, color: TEXT, marginBottom: 6 }}>
                        {catalogue.length === 0 ? 'No resources yet' : 'No resources match your filters'}
                      </div>
                      <div style={{ fontSize: 13 }}>
                        {catalogue.length === 0 ? 'Generate a resource using Quick resource or From a plan to see it here.' : 'Try adjusting your search or type filter.'}
                      </div>
                    </div>
                  )

                  return (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                      {filtered.map(res => {
                        const tc = typeColors[res.resource_type] || { bg: PAGE_BG, color: MUTED }
                        const isViewing = viewingResource?.id === res.id
                        return (
                          <div key={res.id} style={{ border: `0.5px solid ${isViewing ? GREEN : BORDER}`, borderRadius: 10, background: BG, overflow: 'hidden' }}>
                            {/* Row */}
                            <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', cursor: 'pointer' }}
                              onClick={() => setViewingResource(isViewing ? null : res)}>
                              <span style={{ fontSize: 11, fontWeight: 600, background: tc.bg, color: tc.color, padding: '2px 8px', borderRadius: 20, whiteSpace: 'nowrap', flexShrink: 0 }}>
                                {typeLabels[res.resource_type] || res.resource_type}
                              </span>
                              <div style={{ flex: 1, minWidth: 0 }}>
                                <div style={{ fontSize: 13, fontWeight: 500, color: TEXT, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{res.title}</div>
                                <div style={{ fontSize: 11, color: MUTED }}>{res.meta} · {new Date(res.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}</div>
                              </div>
                              <div style={{ display: 'flex', gap: 6, flexShrink: 0 }}>
                                <button
                                  onClick={e => { e.stopPropagation(); setViewingResource(isViewing ? null : res) }}
                                  style={{ height: 26, padding: '0 10px', background: isViewing ? LIGHT_GREEN : PAGE_BG, border: `0.5px solid ${isViewing ? GREEN : BORDER}`, borderRadius: 6, fontSize: 11, fontWeight: 500, color: isViewing ? '#085041' : TEXT, cursor: 'pointer', fontFamily: "'DM Sans', sans-serif" }}>
                                  {isViewing ? 'Hide' : 'View'}
                                </button>
                                <ResourceDownloadButton resource={res} />
                              </div>
                            </div>
                            {/* Expanded view */}
                            {isViewing && (
                              <div style={{ borderTop: `0.5px solid ${BORDER}` }}>
                                {(res.sections || []).map((sec, i) => (
                                  <div key={i} style={{ borderTop: i > 0 ? `0.5px solid ${BORDER}` : 'none' }}>
                                    <div style={{ background: LIGHT_GREEN, padding: '6px 14px', fontSize: 10, fontWeight: 600, color: '#085041', textTransform: 'uppercase', letterSpacing: '0.06em' }}>{sec.heading}</div>
                                    <div style={{ padding: '10px 14px', background: BG, fontSize: 13, color: TEXT, lineHeight: 1.7, whiteSpace: 'pre-wrap' }}>{sec.content}</div>
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                        )
                      })}
                    </div>
                  )
                })()}
              </div>
            )}

          </div>
        </div>

        {/* Error */}
        {error && (
          <div style={{ background: '#FCEBEB', color: '#A32D2D', borderRadius: 8, padding: "0.75rem 1rem", fontSize: 13, marginBottom: 12 }}>{error}</div>
        )}

        {/* Output */}
        {resource && <ResourceOutput resource={resource} />}

        <div style={s.footer}>TeachReads · For UK primary school teachers</div>
      </div>
    </div>
  )
}

// ── My Books Page ─────────────────────────────────────────────────────────────
// (merged My Books + My Library into one page with 3 sections)

// ── Plans Modal ───────────────────────────────────────────────────────────────

